version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CarMarket
    networks:
      - app-network

  app:
    image: carmarket
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CarMarket;UserId=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network: